---
version: '3'

services:
  couchdb-spring:
    image: couchdb
    ports:
      - "5984:5984"

  couchdb-node:
    image: couchdb
    ports:
      - "5985:5984"

  couchdb-go:
    image: couchdb
    ports:
      - "5986:5984"